enableGlobalCache: true

nodeLinker: node-modules
nmMode: hardlinks-global

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.2.0.cjs

packageExtensions:
  babel-plugin-jsx-dom-expressions@*:
    dependencies:
      "@babel/core": "^7.0.0"
